<<<<<<< HEAD
# Generated by Django 3.1.1 on 2024-04-12 17:18

from django.db import migrations, models
=======
# Generated by Django 3.1.1 on 2024-04-10 20:16

from django.db import migrations, models
import uuid
>>>>>>> origin/delete_migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(max_length=500)),
                ('zipcode', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
=======
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a name for your location', max_length=200, unique=True)),
                ('lattitude', models.FloatField()),
                ('longtitude', models.FloatField()),
>>>>>>> origin/delete_migrations
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(default='SOME STRING', help_text='Enter a name for your Map', max_length=200)),
                ('creator', models.CharField(default='SOME STRING', help_text='Enter your name', max_length=200)),
=======
                ('name', models.CharField(help_text='Enter a name for your location', max_length=200)),
>>>>>>> origin/delete_migrations
                ('zoom_level', models.FloatField()),
                ('locations', models.ManyToManyField(related_name='locations', to='maps.Location')),
            ],
        ),
    ]
