# Generated by Django 3.1.1 on 2024-04-08 01:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    # initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a name for your location', max_length=200, unique=True)),
                ('lattitude', models.FloatField()),
                ('longtitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name for your location', max_length=200)),
                ('zoom_level', models.FloatField()),
                ('locations', models.ManyToManyField(related_name='locations', to='maps.Location')),
            ],
        ),
    ]
