# Generated by Django 3.1.1 on 2024-04-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='creator',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
