# Generated by Django 3.1.1 on 2024-04-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20240421_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
