# Generated by Django 3.1.1 on 2024-04-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_map_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='date',
            field=models.DateField(),
        ),
    ]
