# Generated by Django 3.1.1 on 2024-04-18 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_distances'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distances',
            old_name='distance_miles',
            new_name='distance_km',
        ),
    ]
